# **بسم الله الرحمن الرحيم**

# Libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from keras.models import Sequential
from keras.layers import Dense, InputLayer
from keras.utils import to_categorical

# Dataset

In [2]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "zoo.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/zoo-animal-classification",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

df.head()

C:\Users\compumarts\AppData\Local\Temp\ipykernel_1012\609020518.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.2).
Downloading from https://www.kaggle.com/api/v1/datasets/download/uciml/zoo-animal-classification?dataset_version_number=1&file_name=zoo.csv...

100%|██████████| 4.27k/4.27k [00:00<00:00, 280kB/s]

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [3]:
df.head()

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,aardvark,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,antelope,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,bass,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,bear,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,boar,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1

In [4]:
df.info(),df.describe(),df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   animal_name  101 non-null    object
 1   hair         101 non-null    int64
 2   feathers     101 non-null    int64
 3   eggs         101 non-null    int64
 4   milk         101 non-null    int64
 5   airborne     101 non-null    int64
 6   aquatic      101 non-null    int64
 7   predator     101 non-null    int64
 8   toothed      101 non-null    int64
 9   backbone     101 non-null    int64
 10  breathes     101 non-null    int64
 11  venomous     101 non-null    int64
 12  fins         101 non-null    int64
 13  legs         101 non-null    int64
 14  tail         101 non-null    int64
 15  domestic     101 non-null    int64
 16  catsize      101 non-null    int64
 17  class_type   101 non-null    int64
dtypes: int64(17), object(1)
memory usage: 14.3+ KB

(None,
              hair    feathers        eggs        milk    airborne     aquatic  \
 count  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000
 mean     0.425743    0.198020    0.584158    0.405941    0.237624    0.356436
 std      0.496921    0.400495    0.495325    0.493522    0.427750    0.481335
 min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 50%      0.000000    0.000000    1.000000    0.000000    0.000000    0.000000
 75%      1.000000    0.000000    1.000000    1.000000    0.000000    1.000000
 max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

          predator     toothed    backbone    breathes    venomous        fins  \
 count  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000
 mean     0.554455    0.603960    0.821782    0.792079    0.079208    0.168317
 std      0.499505    0.491512    0.384605    0.407844    0.271410    0.376013
 min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 25%      0.000000    0.000000    1.000000    1.000000    0.000000    0.000000
 50%      1.000000    1.000000    1.000000    1.000000    0.000000    0.000000
 75%      1.000000    1.000000    1.000000    1.000000    0.000000    0.000000
 max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

              legs        tail    domestic     catsize  class_type
 count  101.000000  101.000000  101.000000  101.000000  101.000000
 mean     2.841584    0.742574    0.128713    0.435644    2.831683
 std      2.033385    0.439397    0.336552    0.498314    2.102709
 min      0.000000    0.000000    0.000000    0.000000    1.000000
 25%      2.000000    0.000000    0.000000    0.000000    1.000000
 50%      4.000000    1.000000    0.000000    0.000000    2.000000
 75%      4.000000    1.000000    0.000000    1.000000    4.000000
 max      8.000000    1.000000    1.000000    1.000000    7.000000  ,
 animal_name    0
 hair           0
 feathers       0
 eggs           0
 milk           0
 airborne       0
 aquatic        0
 predator       0
 toothed        0
 backbone       0
 breathes       0
 venomous       0
 fins           0
 legs           0
 tail           0
 domestic       0
 catsize        0
 class_type     0
 dtype: int64)

In [5]:
df.info(),df.describe(),df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   animal_name  101 non-null    object
 1   hair         101 non-null    int64
 2   feathers     101 non-null    int64
 3   eggs         101 non-null    int64
 4   milk         101 non-null    int64
 5   airborne     101 non-null    int64
 6   aquatic      101 non-null    int64
 7   predator     101 non-null    int64
 8   toothed      101 non-null    int64
 9   backbone     101 non-null    int64
 10  breathes     101 non-null    int64
 11  venomous     101 non-null    int64
 12  fins         101 non-null    int64
 13  legs         101 non-null    int64
 14  tail         101 non-null    int64
 15  domestic     101 non-null    int64
 16  catsize      101 non-null    int64
 17  class_type   101 non-null    int64
dtypes: int64(17), object(1)
memory usage: 14.3+ KB

(None,
              hair    feathers        eggs        milk    airborne     aquatic  \
 count  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000
 mean     0.425743    0.198020    0.584158    0.405941    0.237624    0.356436
 std      0.496921    0.400495    0.495325    0.493522    0.427750    0.481335
 min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 50%      0.000000    0.000000    1.000000    0.000000    0.000000    0.000000
 75%      1.000000    0.000000    1.000000    1.000000    0.000000    1.000000
 max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

          predator     toothed    backbone    breathes    venomous        fins  \
 count  101.000000  101.000000  101.000000  101.000000  101.000000  101.000000
 mean     0.554455    0.603960    0.821782    0.792079    0.079208    0.168317
 std      0.499505    0.491512    0.384605    0.407844    0.271410    0.376013
 min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000
 25%      0.000000    0.000000    1.000000    1.000000    0.000000    0.000000
 50%      1.000000    1.000000    1.000000    1.000000    0.000000    0.000000
 75%      1.000000    1.000000    1.000000    1.000000    0.000000    0.000000
 max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000

              legs        tail    domestic     catsize  class_type
 count  101.000000  101.000000  101.000000  101.000000  101.000000
 mean     2.841584    0.742574    0.128713    0.435644    2.831683
 std      2.033385    0.439397    0.336552    0.498314    2.102709
 min      0.000000    0.000000    0.000000    0.000000    1.000000
 25%      2.000000    0.000000    0.000000    0.000000    1.000000
 50%      4.000000    1.000000    0.000000    0.000000    2.000000
 75%      4.000000    1.000000    0.000000    1.000000    4.000000
 max      8.000000    1.000000    1.000000    1.000000    7.000000  ,
 animal_name    0
 hair           0
 feathers       0
 eggs           0
 milk           0
 airborne       0
 aquatic        0
 predator       0
 toothed        0
 backbone       0
 breathes       0
 venomous       0
 fins           0
 legs           0
 tail           0
 domestic       0
 catsize        0
 class_type     0
 dtype: int64)

In [6]:
categorical_features = [feature for feature in df.columns if df[feature].dtypes == 'O']
categorical_features

['animal_name']

In [7]:
from sklearn.preprocessing import LabelEncoder
for feature in categorical_features:
    df[feature] = LabelEncoder().fit_transform(df[feature])
df

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,0,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,1,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,2,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,3,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,4,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,95,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1,1
97,96,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0,6
98,97,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
99,98,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,7
100,99,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2

In [8]:
for feature in categorical_features:
    df[feature] = LabelEncoder().fit_transform(df[feature])
df

,animal_name,hair,feathers,eggs,milk,airborne,aquatic,predator,toothed,backbone,breathes,venomous,fins,legs,tail,domestic,catsize,class_type
0,0,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
1,1,1,0,0,1,0,0,0,1,1,1,0,0,4,1,0,1,1
2,2,0,0,1,0,0,1,1,1,1,0,0,1,0,1,0,0,4
3,3,1,0,0,1,0,0,1,1,1,1,0,0,4,0,0,1,1
4,4,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,95,1,0,0,1,0,0,0,1,1,1,0,0,2,1,0,1,1
97,96,1,0,1,0,1,0,0,0,0,1,1,0,6,0,0,0,6
98,97,1,0,0,1,0,0,1,1,1,1,0,0,4,1,0,1,1
99,98,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,7
100,99,0,1,1,0,1,0,0,0,1,1,0,0,2,1,0,0,2

In [9]:
df.columns

Index(['animal_name', 'hair', 'feathers', 'eggs', 'milk', 'airborne',
       'aquatic', 'predator', 'toothed', 'backbone', 'breathes', 'venomous',
       'fins', 'legs', 'tail', 'domestic', 'catsize', 'class_type'],
      dtype='object')

In [10]:
X = df.drop(['animal_name','class_type'], axis=1)
y = df['class_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size  = 0.2, random_state =0 )

In [11]:
X.shape, y.shape

((101, 16), (101,))

In [12]:
X.shape, y.shape

((101, 16), (101,))

# Model

In [13]:
model = Sequential()
model.add(InputLayer(input_shape=(16,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(7, activation='softmax'))

c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\input_layer.py:27: UserWarning: Argument `input_shape` is deprecated. Use `shape` instead.
  warnings.warn(

In [14]:
model = Sequential()
model.add(InputLayer(input_shape=(16,)))
model.add(Dense(16, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(7, activation='softmax'))

In [15]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [17]:
# Convert integer labels to one-hot encoded labels
# Subtract 1 from y_train/y_test because class labels are 1-indexed (1 to 7), and to_categorical expects 0-indexed.
y_train_ohe = to_categorical(y_train - 1, num_classes=y.max())
y_test_ohe = to_categorical(y_test - 1, num_classes=y.max())

model.fit(X_train, y_train_ohe, epochs=100, batch_size=32, validation_data=(X_test, y_test_ohe))

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 9s 1s/step - accuracy: 0.0344 - loss: 2.6009 - val_accuracy: 0.1905 - val_loss: 2.3033
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 93ms/step - accuracy: 0.0422 - loss: 2.4947 - val_accuracy: 0.2381 - val_loss: 2.2449
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.0609 - loss: 2.5119 - val_accuracy: 0.2381 - val_loss: 2.1909
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.0969 - loss: 2.3400 - val_accuracy: 0.2381 - val_loss: 2.1415
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.1227 - loss: 2.2784 - val_accuracy: 0.2381 - val_loss: 2.0964
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.1070 - loss: 2.2061 - val_accuracy: 0.1905 - val_loss: 2.0545
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.1008 - loss: 2.1511 - val_accuracy: 0.1905 - val_loss: 2.0146
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.1086 - loss: 2.1121 - val_accuracy: 0.1905 - val_loss: 1.9786
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.1008 - loss: 2.0530 - val_accuracy: 0.2381 - val_loss: 1.9481
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.1344 - loss: 2.0113 - val_accuracy: 0.2381 - val_loss: 1.9216
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.1328 - loss: 1.9912 - val_accuracy: 0.2381 - val_loss: 1.8976
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.1352 - loss: 1.9446 - val_accuracy: 0.2857 - val_loss: 1.8756
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.1523 - loss: 1.9149 - val_accuracy: 0.2381 - val_loss: 1.8553
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.1047 - loss: 1.8781 - val_accuracy: 0.2857 - val_loss: 1.8365
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.1664 - loss: 1.8547 - val_accuracy: 0.2857 - val_loss: 1.8200
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.2602 - loss: 1.8174 - val_accuracy: 0.2857 - val_loss: 1.8053
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.2844 - loss: 1.8059 - val_accuracy: 0.3333 - val_loss: 1.7909
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.2953 - loss: 1.7935 - val_accuracy: 0.3810 - val_loss: 1.7773
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 0.3211 - loss: 1.7608 - val_accuracy: 0.4762 - val_loss: 1.7639
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.4125 - loss: 1.7238 - val_accuracy: 0.4762 - val_loss: 1.7513
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.4086 - loss: 1.7298 - val_accuracy: 0.4762 - val_loss: 1.7393
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.4930 - loss: 1.6810 - val_accuracy: 0.4762 - val_loss: 1.7277
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.4563 - loss: 1.6799 - val_accuracy: 0.4762 - val_loss: 1.7164
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.4563 - loss: 1.6760 - val_accuracy: 0.4762 - val_loss: 1.7044
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.4992 - loss: 1.6311 - val_accuracy: 0.4762 - val_loss: 1.6929
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.4914 - loss: 1.6105 - val_accuracy: 0.4762 - val_loss: 1.6816
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.4602 - loss: 1.6364 - val_accuracy: 0.5238 - val_loss: 1.6704
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.4914 - loss: 1.5906 - val_accuracy: 0.5238 - val_loss: 1.6592
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.4797 - loss: 1.5863 - val_accuracy: 0.5238 - val_loss: 1.6485
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.4719 - loss: 1.5666 - val_accuracy: 0.5238 - val_loss: 1.6380
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.4602 - loss: 1.5882 - val_accuracy: 0.5238 - val_loss: 1.6262
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5031 - loss: 1.5181 - val_accuracy: 0.5238 - val_loss: 1.6147
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - accuracy: 0.4719 - loss: 1.5241 - val_accuracy: 0.5238 - val_loss: 1.6033
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.4961 - loss: 1.5246 - val_accuracy: 0.5714 - val_loss: 1.5900
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - accuracy: 0.5000 - loss: 1.5190 - val_accuracy: 0.5714 - val_loss: 1.5761
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.4727 - loss: 1.5115 - val_accuracy: 0.5714 - val_loss: 1.5619
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.5234 - loss: 1.4500 - val_accuracy: 0.5714 - val_loss: 1.5474
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5063 - loss: 1.4568 - val_accuracy: 0.5714 - val_loss: 1.5329
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5109 - loss: 1.4809 - val_accuracy: 0.5714 - val_loss: 1.5182
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5578 - loss: 1.4244 - val_accuracy: 0.5714 - val_loss: 1.5041
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5148 - loss: 1.4352 - val_accuracy: 0.5714 - val_loss: 1.4902
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5344 - loss: 1.4386 - val_accuracy: 0.5714 - val_loss: 1.4760
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5422 - loss: 1.3856 - val_accuracy: 0.5714 - val_loss: 1.4622
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5539 - loss: 1.3746 - val_accuracy: 0.5714 - val_loss: 1.4494
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5344 - loss: 1.3731 - val_accuracy: 0.5714 - val_loss: 1.4369
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.5500 - loss: 1.3316 - val_accuracy: 0.5714 - val_loss: 1.4247
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5266 - loss: 1.3664 - val_accuracy: 0.5714 - val_loss: 1.4128
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5383 - loss: 1.3565 - val_accuracy: 0.5714 - val_loss: 1.4007
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5133 - loss: 1.3534 - val_accuracy: 0.5714 - val_loss: 1.3885
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.5680 - loss: 1.2732 - val_accuracy: 0.5714 - val_loss: 1.3762
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5602 - loss: 1.2868 - val_accuracy: 0.5714 - val_loss: 1.3633
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5602 - loss: 1.3004 - val_accuracy: 0.5714 - val_loss: 1.3506
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.5641 - loss: 1.2554 - val_accuracy: 0.5714 - val_loss: 1.3383
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5719 - loss: 1.2340 - val_accuracy: 0.5714 - val_loss: 1.3257
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.5562 - loss: 1.2337 - val_accuracy: 0.5714 - val_loss: 1.3127
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - accuracy: 0.5406 - loss: 1.2593 - val_accuracy: 0.5714 - val_loss: 1.3007
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5641 - loss: 1.2087 - val_accuracy: 0.5714 - val_loss: 1.2889
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5133 - loss: 1.2810 - val_accuracy: 0.5714 - val_loss: 1.2769
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 109ms/step - accuracy: 0.5523 - loss: 1.1955 - val_accuracy: 0.5714 - val_loss: 1.2648
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 191ms/step - accuracy: 0.5211 - loss: 1.2153 - val_accuracy: 0.5714 - val_loss: 1.2534
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 255ms/step - accuracy: 0.5719 - loss: 1.1775 - val_accuracy: 0.5714 - val_loss: 1.2424
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 171ms/step - accuracy: 0.5680 - loss: 1.1531 - val_accuracy: 0.5714 - val_loss: 1.2317
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 109ms/step - accuracy: 0.5914 - loss: 1.1439 - val_accuracy: 0.5714 - val_loss: 1.2209
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5922 - loss: 1.1538 - val_accuracy: 0.5714 - val_loss: 1.2105
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step - accuracy: 0.5766 - loss: 1.1241 - val_accuracy: 0.5714 - val_loss: 1.2005
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5961 - loss: 1.1112 - val_accuracy: 0.5714 - val_loss: 1.1908
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6109 - loss: 1.1595 - val_accuracy: 0.5714 - val_loss: 1.1812
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6422 - loss: 1.0596 - val_accuracy: 0.5714 - val_loss: 1.1715
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - accuracy: 0.6031 - loss: 1.1049 - val_accuracy: 0.5714 - val_loss: 1.1618
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5719 - loss: 1.1702 - val_accuracy: 0.5714 - val_loss: 1.1522
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5859 - loss: 1.1352 - val_accuracy: 0.5714 - val_loss: 1.1428
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6250 - loss: 1.1095 - val_accuracy: 0.5714 - val_loss: 1.1329
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6055 - loss: 1.1352 - val_accuracy: 0.5714 - val_loss: 1.1231
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6289 - loss: 1.0648 - val_accuracy: 0.5714 - val_loss: 1.1142
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.6484 - loss: 1.0420 - val_accuracy: 0.5714 - val_loss: 1.1049
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6484 - loss: 0.9957 - val_accuracy: 0.6190 - val_loss: 1.0962
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.5703 - loss: 1.1383 - val_accuracy: 0.6190 - val_loss: 1.0879
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.5898 - loss: 1.0831 - val_accuracy: 0.6190 - val_loss: 1.0800
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6211 - loss: 1.0326 - val_accuracy: 0.6190 - val_loss: 1.0722
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6289 - loss: 1.0357 - val_accuracy: 0.6190 - val_loss: 1.0637
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6070 - loss: 1.0583 - val_accuracy: 0.6190 - val_loss: 1.0552
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6187 - loss: 1.0068 - val_accuracy: 0.6190 - val_loss: 1.0470
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.6227 - loss: 0.9951 - val_accuracy: 0.6190 - val_loss: 1.0385
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6266 - loss: 0.9768 - val_accuracy: 0.6190 - val_loss: 1.0305
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5992 - loss: 1.0365 - val_accuracy: 0.6190 - val_loss: 1.0225
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6148 - loss: 0.9717 - val_accuracy: 0.6190 - val_loss: 1.0141
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - accuracy: 0.5719 - loss: 1.0316 - val_accuracy: 0.6190 - val_loss: 1.0057
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5797 - loss: 1.0033 - val_accuracy: 0.6190 - val_loss: 0.9973
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 337ms/step - accuracy: 0.6383 - loss: 0.9007 - val_accuracy: 0.6190 - val_loss: 0.9895
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6070 - loss: 0.9742 - val_accuracy: 0.6190 - val_loss: 0.9813
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 0.5914 - loss: 0.9490 - val_accuracy: 0.6190 - val_loss: 0.9736
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6187 - loss: 0.9394 - val_accuracy: 0.6190 - val_loss: 0.9653
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.6070 - loss: 0.9397 - val_accuracy: 0.6190 - val_loss: 0.9581
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 215ms/step - accuracy: 0.6008 - loss: 0.9403 - val_accuracy: 0.6190 - val_loss: 0.9511
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5828 - loss: 0.9407 - val_accuracy: 0.6190 - val_loss: 0.9450
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6180 - loss: 0.8755 - val_accuracy: 0.6190 - val_loss: 0.9390
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6023 - loss: 0.8758 - val_accuracy: 0.6190 - val_loss: 0.9330
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.5516 - loss: 0.9646 - val_accuracy: 0.6190 - val_loss: 0.9275
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5906 - loss: 0.8766 - val_accuracy: 0.6190 - val_loss: 0.9216
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5906 - loss: 0.8769 - val_accuracy: 0.6190 - val_loss: 0.9159

In [18]:
# Convert integer labels to one-hot encoded labels
# Subtract 1 from y_train/y_test because class labels are 1-indexed (1 to 7), and to_categorical expects 0-indexed.
y_train_ohe = to_categorical(y_train - 1, num_classes=y.max())
y_test_ohe = to_categorical(y_test - 1, num_classes=y.max())

model.fit(X_train, y_train_ohe, epochs=100, batch_size=32, validation_data=(X_test, y_test_ohe))

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - accuracy: 0.5945 - loss: 0.8822 - val_accuracy: 0.6190 - val_loss: 0.9095
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6023 - loss: 0.8800 - val_accuracy: 0.6190 - val_loss: 0.9031
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - accuracy: 0.5711 - loss: 0.9183 - val_accuracy: 0.6190 - val_loss: 0.8975
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6102 - loss: 0.8609 - val_accuracy: 0.6190 - val_loss: 0.8923
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6180 - loss: 0.8011 - val_accuracy: 0.6190 - val_loss: 0.8873
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.6258 - loss: 0.8128 - val_accuracy: 0.6190 - val_loss: 0.8818
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5789 - loss: 0.8524 - val_accuracy: 0.6190 - val_loss: 0.8770
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5555 - loss: 0.9125 - val_accuracy: 0.6190 - val_loss: 0.8722
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6023 - loss: 0.8362 - val_accuracy: 0.6190 - val_loss: 0.8678
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.5789 - loss: 0.8646 - val_accuracy: 0.6190 - val_loss: 0.8629
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.5984 - loss: 0.8294 - val_accuracy: 0.6190 - val_loss: 0.8587
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5789 - loss: 0.8948 - val_accuracy: 0.6190 - val_loss: 0.8548
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6023 - loss: 0.8145 - val_accuracy: 0.6190 - val_loss: 0.8506
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.5984 - loss: 0.8521 - val_accuracy: 0.6190 - val_loss: 0.8465
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5672 - loss: 0.8736 - val_accuracy: 0.6190 - val_loss: 0.8430
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5711 - loss: 0.8543 - val_accuracy: 0.6190 - val_loss: 0.8396
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 110ms/step - accuracy: 0.5867 - loss: 0.8161 - val_accuracy: 0.6190 - val_loss: 0.8357
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5828 - loss: 0.8458 - val_accuracy: 0.6190 - val_loss: 0.8315
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5828 - loss: 0.8008 - val_accuracy: 0.6190 - val_loss: 0.8276
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6062 - loss: 0.7759 - val_accuracy: 0.6190 - val_loss: 0.8236
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5477 - loss: 0.8490 - val_accuracy: 0.6190 - val_loss: 0.8201
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5945 - loss: 0.8102 - val_accuracy: 0.6190 - val_loss: 0.8163
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - accuracy: 0.5984 - loss: 0.7735 - val_accuracy: 0.6190 - val_loss: 0.8119
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 97ms/step - accuracy: 0.5945 - loss: 0.7732 - val_accuracy: 0.6190 - val_loss: 0.8075
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.5633 - loss: 0.8321 - val_accuracy: 0.6190 - val_loss: 0.8036
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5945 - loss: 0.7649 - val_accuracy: 0.6190 - val_loss: 0.7992
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - accuracy: 0.5945 - loss: 0.7969 - val_accuracy: 0.6190 - val_loss: 0.7944
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6062 - loss: 0.7348 - val_accuracy: 0.6190 - val_loss: 0.7905
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5828 - loss: 0.7763 - val_accuracy: 0.6190 - val_loss: 0.7873
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5437 - loss: 0.8472 - val_accuracy: 0.6190 - val_loss: 0.7834
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5789 - loss: 0.8038 - val_accuracy: 0.6190 - val_loss: 0.7790
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.5906 - loss: 0.7929 - val_accuracy: 0.6190 - val_loss: 0.7743
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5828 - loss: 0.7549 - val_accuracy: 0.6190 - val_loss: 0.7703
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.5828 - loss: 0.7767 - val_accuracy: 0.6190 - val_loss: 0.7682
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.5867 - loss: 0.7497 - val_accuracy: 0.6190 - val_loss: 0.7664
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 94ms/step - accuracy: 0.6062 - loss: 0.7383 - val_accuracy: 0.6190 - val_loss: 0.7642
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6141 - loss: 0.7081 - val_accuracy: 0.6190 - val_loss: 0.7621
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6102 - loss: 0.7273 - val_accuracy: 0.6190 - val_loss: 0.7592
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.6180 - loss: 0.7227 - val_accuracy: 0.6190 - val_loss: 0.7565
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.5594 - loss: 0.7650 - val_accuracy: 0.6190 - val_loss: 0.7536
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5750 - loss: 0.7644 - val_accuracy: 0.6190 - val_loss: 0.7502
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - accuracy: 0.6219 - loss: 0.6987 - val_accuracy: 0.6190 - val_loss: 0.7463
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 107ms/step - accuracy: 0.5906 - loss: 0.7069 - val_accuracy: 0.6190 - val_loss: 0.7434
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.5555 - loss: 0.7613 - val_accuracy: 0.6190 - val_loss: 0.7415
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6164 - loss: 0.6845 - val_accuracy: 0.6190 - val_loss: 0.7399
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step - accuracy: 0.6047 - loss: 0.7345 - val_accuracy: 0.6190 - val_loss: 0.7387
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.5500 - loss: 0.7801 - val_accuracy: 0.6190 - val_loss: 0.7367
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.5617 - loss: 0.7882 - val_accuracy: 0.6190 - val_loss: 0.7349
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.5891 - loss: 0.7434 - val_accuracy: 0.6190 - val_loss: 0.7321
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.6125 - loss: 0.6966 - val_accuracy: 0.6190 - val_loss: 0.7297
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 112ms/step - accuracy: 0.6164 - loss: 0.6923 - val_accuracy: 0.6190 - val_loss: 0.7260
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.5891 - loss: 0.7243 - val_accuracy: 0.6190 - val_loss: 0.7224
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.6164 - loss: 0.6948 - val_accuracy: 0.6190 - val_loss: 0.7189
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step - accuracy: 0.5852 - loss: 0.7217 - val_accuracy: 0.6190 - val_loss: 0.7164
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6625 - loss: 0.6808 - val_accuracy: 0.6190 - val_loss: 0.7135
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.6117 - loss: 0.7116 - val_accuracy: 0.6190 - val_loss: 0.7099
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 92ms/step - accuracy: 0.6234 - loss: 0.7249 - val_accuracy: 0.6190 - val_loss: 0.7073
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step - accuracy: 0.6508 - loss: 0.6738 - val_accuracy: 0.6190 - val_loss: 0.7043
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - accuracy: 0.6117 - loss: 0.6935 - val_accuracy: 0.6190 - val_loss: 0.7026
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - accuracy: 0.6234 - loss: 0.7083 - val_accuracy: 0.6190 - val_loss: 0.7009
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.6805 - loss: 0.6441 - val_accuracy: 0.6190 - val_loss: 0.6986
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 145ms/step - accuracy: 0.6453 - loss: 0.7116 - val_accuracy: 0.6190 - val_loss: 0.6963
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 106ms/step - accuracy: 0.6727 - loss: 0.6554 - val_accuracy: 0.6190 - val_loss: 0.6934
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 105ms/step - accuracy: 0.6844 - loss: 0.6230 - val_accuracy: 0.6190 - val_loss: 0.6908
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - accuracy: 0.6727 - loss: 0.6480 - val_accuracy: 0.6190 - val_loss: 0.6883
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - accuracy: 0.6648 - loss: 0.6577 - val_accuracy: 0.6190 - val_loss: 0.6859
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step - accuracy: 0.6609 - loss: 0.6680 - val_accuracy: 0.6190 - val_loss: 0.6840
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 187ms/step - accuracy: 0.6414 - loss: 0.6794 - val_accuracy: 0.6190 - val_loss: 0.6823
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 125ms/step - accuracy: 0.6727 - loss: 0.6429 - val_accuracy: 0.6190 - val_loss: 0.6794
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - accuracy: 0.6492 - loss: 0.6926 - val_accuracy: 0.6190 - val_loss: 0.6755
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 122ms/step - accuracy: 0.6570 - loss: 0.6599 - val_accuracy: 0.6190 - val_loss: 0.6717
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - accuracy: 0.6219 - loss: 0.6990 - val_accuracy: 0.6190 - val_loss: 0.6684
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.6453 - loss: 0.6341 - val_accuracy: 0.6190 - val_loss: 0.6658
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - accuracy: 0.6414 - loss: 0.6434 - val_accuracy: 0.6190 - val_loss: 0.6647
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 171ms/step - accuracy: 0.6219 - loss: 0.6570 - val_accuracy: 0.5714 - val_loss: 0.6635
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.6687 - loss: 0.6059 - val_accuracy: 0.5714 - val_loss: 0.6621
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - accuracy: 0.6336 - loss: 0.6734 - val_accuracy: 0.5714 - val_loss: 0.6616
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - accuracy: 0.6102 - loss: 0.6740 - val_accuracy: 0.5714 - val_loss: 0.6607
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step - accuracy: 0.6805 - loss: 0.5931 - val_accuracy: 0.5714 - val_loss: 0.6594
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.6984 - loss: 0.5989 - val_accuracy: 0.5714 - val_loss: 0.6584
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6812 - loss: 0.6171 - val_accuracy: 0.5714 - val_loss: 0.6574
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.6656 - loss: 0.6155 - val_accuracy: 0.5714 - val_loss: 0.6573
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6812 - loss: 0.6109 - val_accuracy: 0.5714 - val_loss: 0.6556
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 101ms/step - accuracy: 0.6969 - loss: 0.5651 - val_accuracy: 0.5714 - val_loss: 0.6545
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6695 - loss: 0.6240 - val_accuracy: 0.5714 - val_loss: 0.6528
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 87ms/step - accuracy: 0.6953 - loss: 0.5890 - val_accuracy: 0.5714 - val_loss: 0.6502
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6836 - loss: 0.5818 - val_accuracy: 0.5714 - val_loss: 0.6482
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.7031 - loss: 0.5600 - val_accuracy: 0.5714 - val_loss: 0.6484
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.7109 - loss: 0.5725 - val_accuracy: 0.5714 - val_loss: 0.6497
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.6680 - loss: 0.6006 - val_accuracy: 0.5714 - val_loss: 0.6497
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.6797 - loss: 0.5815 - val_accuracy: 0.5714 - val_loss: 0.6501
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7031 - loss: 0.5745 - val_accuracy: 0.5714 - val_loss: 0.6503
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7328 - loss: 0.5325 - val_accuracy: 0.5714 - val_loss: 0.6498
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.7289 - loss: 0.5459 - val_accuracy: 0.5714 - val_loss: 0.6483
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.7078 - loss: 0.5501 - val_accuracy: 0.5714 - val_loss: 0.6462
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.7156 - loss: 0.5775 - val_accuracy: 0.5714 - val_loss: 0.6440
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.7039 - loss: 0.5605 - val_accuracy: 0.5714 - val_loss: 0.6410
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - accuracy: 0.7156 - loss: 0.5659 - val_accuracy: 0.6190 - val_loss: 0.6384
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - accuracy: 0.6961 - loss: 0.5715 - val_accuracy: 0.6190 - val_loss: 0.6356
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - accuracy: 0.7195 - loss: 0.5628 - val_accuracy: 0.6190 - val_loss: 0.6325

In [19]:
model.predict(X_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 186ms/step

array([[4.45508324e-02, 5.90047166e-02, 2.09077910e-01, 9.15964991e-02,
        6.82747513e-02, 1.83836818e-02, 5.09111583e-01],
       [2.73677433e-04, 1.70559157e-04, 2.36205459e-01, 7.40220904e-01,
        1.26559520e-03, 1.02469421e-04, 2.17613950e-02],
       [4.12255147e-04, 2.23631694e-04, 1.65389583e-01, 8.14025283e-01,
        1.38670090e-03, 3.24867986e-04, 1.82377137e-02],
       [9.48489606e-01, 4.74978238e-02, 4.12887282e-04, 1.87885293e-04,
        5.05815435e-04, 2.86061596e-03, 4.53055400e-05],
       [9.78749812e-01, 1.87250841e-02, 2.05622753e-04, 1.62545504e-04,
        1.38715186e-04, 2.00747792e-03, 1.07649485e-05],
       [8.99046063e-01, 9.20835510e-02, 1.08722912e-03, 4.33469948e-04,
        1.66370801e-03, 5.48587926e-03, 2.00179915e-04],
       [3.65903854e-01, 3.19805413e-01, 6.34955093e-02, 4.66100611e-02,
        7.63155892e-02, 8.09587762e-02, 4.69107963e-02],
       [8.18043191e-04, 4.55246191e-04, 1.55541584e-01, 8.18300009e-01,
        2.21216236e-03, 8.70627642e-04, 2.18023174e-02],
       [8.89505804e-01, 1.03568420e-01, 8.10763915e-04, 2.40924477e-04,
        1.60032185e-03, 4.10476653e-03, 1.69066931e-04],
       [9.48357701e-01, 4.43699211e-02, 7.95843021e-04, 5.67777024e-04,
        6.74496347e-04, 5.15532214e-03, 7.89741316e-05],
       [2.04710867e-02, 1.88488595e-03, 4.85538883e-04, 3.22757667e-04,
        1.10518513e-03, 5.29560864e-01, 4.46169734e-01],
       [8.93715143e-01, 9.67376903e-02, 1.18584186e-03, 4.71764564e-04,
        1.83427928e-03, 5.82828186e-03, 2.27024851e-04],
       [3.53790015e-01, 3.18295836e-01, 6.59430921e-02, 4.93607782e-02,
        7.90451393e-02, 8.38009417e-02, 4.97642010e-02],
       [5.30711226e-02, 1.07979663e-01, 3.34115922e-01, 1.60635576e-01,
        1.05433598e-01, 1.06572695e-02, 2.28106871e-01],
       [7.25104823e-04, 2.92716228e-04, 1.28863737e-01, 8.52912545e-01,
        1.43621839e-03, 7.37322669e-04, 1.50323678e-02],
       [2.29679625e-02, 3.74740572e-03, 1.25729281e-03, 1.00709777e-03,
        2.60135694e-03, 5.06345332e-01, 4.62073535e-01],
       [9.48489606e-01, 4.74978238e-02, 4.12887282e-04, 1.87885293e-04,
        5.05815435e-04, 2.86061596e-03, 4.53055400e-05],
       [1.26709929e-02, 3.53949261e-03, 3.34733282e-03, 2.46905605e-03,
        4.15226445e-03, 2.28834227e-01, 7.44986653e-01],
       [3.53790045e-01, 3.18295866e-01, 6.59430772e-02, 4.93607819e-02,
        7.90451467e-02, 8.38009566e-02, 4.97641936e-02],
       [4.12255118e-04, 2.23631898e-04, 1.65389687e-01, 8.14025223e-01,
        1.38670218e-03, 3.24867957e-04, 1.82377268e-02],
       [3.68140280e-01, 3.19921881e-01, 5.81093170e-02, 4.48145047e-02,
        7.47566149e-02, 8.98746848e-02, 4.43827063e-02]], dtype=float32)

In [20]:
pred = (model.predict(X_test) > 0.5).astype(int)[:,0]
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step

array([0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [21]:
print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      1.00      1.00         7
           2       0.00      0.00      0.00         4
           4       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         1
           6       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         2

    accuracy                           0.33        21
   macro avg       0.14      0.14      0.14        21
weighted avg       0.33      0.33      0.33        21

c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
c:\Users\compumarts\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [22]:
model.save("animal_class.keras")

In [23]:
import joblib
from sklearn.preprocessing import StandardScaler

# Initialize and fit the scalar to resolve the NameError.
# Note: The model was trained on unscaled data. For a complete pipeline,
# scaling should be applied to X_train and X_test before model training.
scalar = StandardScaler()
scalar.fit(X_train)

joblib.dump(scalar, "ac_scalar.pkl")

['ac_scalar.pkl']

In [24]:
joblib.load("ac_scalar.pkl")

StandardScaler()